# Generated by Django 3.2.11 on 2022-01-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_desenvolvedor', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='fotos_perfil')),
                ('titulo_desenvolvedor', models.CharField(max_length=255)),
                ('email_desenvolvedor', models.CharField(max_length=255)),
                ('linkedin_desenvolvedor', models.URLField()),
                ('github_desenvolvedor', models.URLField()),
                ('descricao_desenvolvedor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=255)),
                ('is_top_3', models.BooleanField(default=False)),
                ('is_tec', models.BooleanField(default=False)),
                ('is_professional', models.BooleanField(default=False)),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.desenvolvedor')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('dev_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.desenvolvedor')),
            ],
        ),
    ]
